testing_mode = true
payment_provider = "stripe" #bmac if using Buy Me A Coffee
stripe_api_key_test = "sk_test_51OEP9VDvYq7iSz1po6HfNfJHsmXKurfUKCfaOkqEEYWS8IXwPTWhNHGKDqQsKSCDxa3VGVBbmwEZozuwKdM5Zf8X00tBJw9cG0" #only needed if using Stripe
stripe_api_key = "sk_live_..." #only needed if using Stripe
stripe_link = "https://buy.stripe.com/..." #only needed if using Stripe
stripe_link_test = "https://buy.stripe.com/test_9AQ3eh0NAcPifew14c" #only needed if using Stripe
client_id = "590..."
client_secret = "GO..."
redirect_url_test = 'http://localhost:8501/'
redirect_url = ""
